name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          mkdir -p ./build &&
          docker build --tag pulseaudio-win32 --build-arg "PAW32_VERSION=$(echo "$(git describe --always --tags)" | sed -e "s/^v//g")" ./src &&
          docker save pulseaudio-win32 |
          tar -xvf - -C ./build &&
          tar -xvf ./build/blobs/sha256/$(ls -1S ./build/blobs/sha256|head -n1) -C ./build
      - name: Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          draft: true
          prerelease: false
          working_directory: build
          files: |
            pasetup.exe
            pulseaudio.zip
